public class Main {
    public static void main(String[] args){
        CustomList list = new CustomList();
        System.out.println("-----------------------");
        System.out.println(list.isEmpty());
        System.out.println("-----------------------");
        list.addInTheStart(10);
        list.addInTheEnd(12);
        System.out.println("-----------------------");
        System.out.println(list.isEmpty());
        System.out.println("-----------------------");
        list.addInTheStart(5);
        list.deleteLast();
        list.addInTheStart(11);
        System.out.println("-----------------------");
        list.print();
        System.out.println("-----------------------");
        System.out.println("-----------------------");
        list.elementEntryIndexes(10);
        System.out.println("-----------------------");
        list.addInTheStart(10);
        System.out.println("-----------------------");
        list.print();
        System.out.println("-----------------------");
        System.out.println("-----------------------");
        list.elementEntryIndexes(10);
        System.out.println("-----------------------");
        System.out.println("-----------------------");
        System.out.println(list.elementEntry(5));
        System.out.println("-----------------------");
        System.out.println("-----------------------");
        System.out.println(list.size());
        System.out.println("-----------------------");
        System.out.println("-----------------------");
        list.print();
        System.out.println("-----------------------");
        System.out.println("-----------------------");
        list.reverse();
        System.out.println("-----------------------");
    }
}
